-- ============================================================
-- 遷移：保留現有資料,拆分共享庫存架構
--   舊 items（含 qty/warehouse） → items（共享資訊） + item_variants（各倉庫庫存）
--
-- 特點：
--   • 完全保留現有資料,不清空
--   • items.id 保持不變 → item_batches 的 item_id 引用不會壞
--   • item_batches 表完全不動（已有 item_id + warehouse_id）
--   • 整段包在 transaction 裡,失敗會自動全部回滾
--
-- 使用：Supabase → SQL Editor,整段貼上,執行一次即可
-- ============================================================

BEGIN;

-- 0) people 加 is_admin 欄位（給「倉庫管理員」用）
ALTER TABLE people ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;

-- 1) 備份舊 items（萬一要還原）
DROP TABLE IF EXISTS items_backup;
CREATE TABLE items_backup AS TABLE items;

-- 2) 建立 item_variants（各倉庫獨立庫存）
--    item_id 用 BIGINT 配合舊 items.id（你的 items.id 是 bigint,不是 UUID）
CREATE TABLE IF NOT EXISTS item_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL,
  warehouse_id TEXT NOT NULL,
  qty INT DEFAULT 0,
  critical_qty INT DEFAULT 0,
  storage_photo_url TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now(),
  UNIQUE(item_id, warehouse_id)
);

-- 3) 把舊 items 的庫存資料灌進 item_variants
--    item_id = 舊 items.id（不變）；warehouse_id 為 NULL 的歸到 HARDWARE（五金原料 = 原始倉庫）
INSERT INTO item_variants (item_id, warehouse_id, qty, critical_qty, storage_photo_url)
SELECT
  id,
  COALESCE(NULLIF(warehouse_id, ''), 'HARDWARE'),
  COALESCE(qty, 0),
  COALESCE(critical_qty, 0),
  storage_photo_url
FROM items
ON CONFLICT (item_id, warehouse_id) DO NOTHING;

-- 4) 從 items 移除「各倉庫」欄位,只留共享資訊
ALTER TABLE items DROP COLUMN IF EXISTS qty;
ALTER TABLE items DROP COLUMN IF EXISTS critical_qty;
ALTER TABLE items DROP COLUMN IF EXISTS storage_photo_url;
ALTER TABLE items DROP COLUMN IF EXISTS warehouse_id;

-- 5) 建立外鍵（PostgREST 需要這個才能做 item_variants → items(*) 的 join 查詢）
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_variant_item') THEN
    ALTER TABLE item_variants
      ADD CONSTRAINT fk_variant_item
      FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE;
  END IF;
END $$;

-- 5b) 建立 item_batches（批次/FIFO；你的資料庫還沒有這張表）
CREATE TABLE IF NOT EXISTS item_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  warehouse_id TEXT,
  lot_no TEXT,
  code_produksi TEXT,
  po_no TEXT,
  do_no TEXT,
  production_date DATE,
  expiry_date DATE,
  shelf_life TEXT,
  qty_initial INT DEFAULT 0,
  qty_remaining INT DEFAULT 0,
  received_date DATE,
  qc_status TEXT,
  qc_date DATE,
  coa_url TEXT,
  created_at TIMESTAMP DEFAULT now()
);

-- 6) 索引（加速查詢與切換倉庫）
CREATE INDEX IF NOT EXISTS idx_items_name        ON items(name);
CREATE INDEX IF NOT EXISTS idx_variants_item     ON item_variants(item_id);
CREATE INDEX IF NOT EXISTS idx_variants_wh       ON item_variants(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_batches_item      ON item_batches(item_id);
CREATE INDEX IF NOT EXISTS idx_batches_wh        ON item_batches(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_batches_expiry    ON item_batches(expiry_date);

COMMIT;

-- ============================================================
-- 驗證（執行完後可單獨跑這幾行檢查）
-- ============================================================
-- SELECT count(*) AS items_count FROM items;
-- SELECT warehouse_id, count(*) AS variant_count FROM item_variants GROUP BY warehouse_id ORDER BY warehouse_id;
-- SELECT name, warehouses, is_admin FROM people ORDER BY name;

-- ============================================================
-- 還原（萬一要退回舊架構,才執行這段；平常不要碰）
-- ============================================================
-- BEGIN;
-- DROP TABLE IF EXISTS item_variants;
-- DROP TABLE IF EXISTS items;
-- ALTER TABLE items_backup RENAME TO items;
-- COMMIT;
