-- ============================================================
-- 補建：transactions（交易紀錄）+ requests（叫貨申請）
--   你的資料庫還沒有這兩張表 → App 取貨/入庫/叫貨時會用到
--   不加外鍵：刪掉商品或人員後,歷史紀錄仍保留
--   在 Supabase → SQL Editor 整段執行一次
-- ============================================================

BEGIN;

-- 交易紀錄（取貨 ambil / 入庫 masuk / 盤點 opname）
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT,
  item_id BIGINT,
  item_name TEXT,
  person_id BIGINT,
  person_name TEXT,
  qty INT,
  warehouse_id TEXT,
  created_at TIMESTAMP DEFAULT now()
);

-- 叫貨申請
CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_name TEXT,
  items_requested TEXT,
  note TEXT,
  status TEXT DEFAULT 'pending',
  warehouse_id TEXT,
  created_at TIMESTAMP DEFAULT now()
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_tx_created  ON transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_tx_wh       ON transactions(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_req_wh      ON requests(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_req_status  ON requests(status);

COMMIT;
